# Generated by Django 2.2.6 on 2019-10-30 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0006_listing_is_in_spotlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('photo_front', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_back', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_left', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_right', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_extra', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_extra2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('photo_file2', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
