# Generated by Django 2.2.6 on 2019-10-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='photo_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='photo_file2',
            new_name='file2',
        ),
    ]
