# Generated by Django 2.2.6 on 2019-10-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_auto_20191031_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_back',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_extra',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_extra2',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_front',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_left',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='photo_right',
        ),
    ]
