# Generated by Django 2.2.6 on 2019-10-31 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_auto_20191031_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
