# Generated by Django 2.2.6 on 2019-11-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_auto_20191031_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
