# Generated by Django 2.2.6 on 2019-10-23 19:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('millage', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('cc', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('photo_front', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_back', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_left', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_right', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_extra', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_extra2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
