# Generated by Django 2.2.6 on 2019-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191023_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cc',
            field=models.IntegerField(default=0),
        ),
    ]
