# Generated by Django 2.2.6 on 2019-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20191023_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_in_spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
