# Generated by Django 2.2.6 on 2019-11-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20191101_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
