car_make_choices = {
  'Acura':'Acura', 
  'Alfa-Romeo':'Alfa-Romeo', 
  'Aston-Martin':'Aston-Martin', 
  'Audi':'Audi', 
  'Bentley':'Bentley', 
  'BMW':'BMW', 
  'Bugatti':'Bugatti', 
  'Buick':'Buick', 
  'Cadillac':'Cadillac', 
  'Chevrolet':'Chevrolet', 
  'Chrysler':'Chrysler', 
  'Citroen':'Citroen', 
  'Dodge':'Dodge', 
  'Ferrari':'Ferrari', 
  'Fiat':'Fiat', 
  'Ford':'Ford', 
  'Geely':'Geely', 
  'Genesis':'Genesis', 
  'GMC':'GMC', 
  'Honda':'Honda', 
  'Hyundai':'Hyundai', 
  'Infiniti':'Infiniti', 
  'Jaguar':'Jaguar', 
  'Jeep':'Jeep', 
  'Kia':'Kia', 
  'Koenigsegg':'Koenigsegg', 
  'Lamborghini':'Lamborghini', 
  'Lancia':'Lancia', 
  'Land Rover':'Land Rover', 
  'Lexus':'Lexus', 
  'Lincoln':'Lincoln', 
  'Lotus':'Lotus', 
  'Maserati':'Maserati', 
  'Maybach':'Maybach', 
  'Mazda':'Mazda', 
  'Mclaren':'Mclaren', 
  'Mercedes':'Mercedes', 
  'Mini':'Mini', 
  'Mitsubishi':'Mitsubishi', 
  'Nissan':'Nissan', 
  'Opel':'Opel', 
  'Pagani':'Pagani', 
  'Peugeot':'Peugeot', 
  'Pontiac':'Pontiac',
  'Porsche':'Porsche', 
  'Ram':'Ram', 
  'Renault':'Renault', 
  'Rolls-Royce':'Rolls-Royce', 
  'Skoda':'Skoda', 
  'Smart':'Smart', 
  'Subaru':'Subaru', 
  'Suzuki':'Suzuki', 
  'Tesla':'Tesla', 
  'Toyota':'Toyota', 
  'Volkswagen':'Volkswagen', 
  'Volvo':'Volvo',
  'Other':'Other'
  }

moto_make_choices = {
  'Aprilia':'Aprilia',
  'Benelli': 'Benelli',
  'BMW': 'BMW',
  'Ducati': 'Ducati',
  'Honda': 'Honda',
  'Indian': 'Indian',
  'Kawasaki':'Kawasaki',
  'Keeway': 'Keeway',
  'KTM':'KTM',
  'Suzuki': 'Suzuki',
  'Triumph': 'Triumph',
  'Yamaha':'Yamaha'
  }
